### PR TITLE
Configurable enum

### PR DESCRIPTION
**Pull request by yann-eugone**
see #24 

- [x] Add the 2 configurable enum classes to the source code
- [x] Add testing for those two classes
- [x] Add more documentation about usage and examples
- [x] Add enum autoconfiguration within the bundle extension

### CODE REVIEW

**Comment by yann-eugone** [comment]
@J-Ben87 what do you think ?

- https://github.com/yokai-php/enum-bundle/blob/configurable-enum/README.md
- https://github.com/yokai-php/enum-bundle/blob/configurable-enum/Resources/doc/declaring-enum.md

**Comment by J-Ben87** [comment]
I like it! You allowed the different solution in a non intrusive way, I can't think of a better solution.

**Comment by yann-eugone** [comment]
What about the documentation ? Do you think it is clear enough ?

**Comment by J-Ben87** [comment]
I think so. Maybe because I already know how to use it, but it seems pretty clear. You detailed all the ways to declare enums, how to integrate it with Sonata...
Maybe you could add a little note on how to use it in forms without type guessing, or on how to use the translated enum.

**Comment by yann-eugone** [comment]
Just added more documentation, and fixed some important inconsistent issues with namespaces (from symfony 3 to symfony 4 conventions)

**Pull request merged**
